### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by suhlig** [aqua/raspberrypi#2]
Hi,

I came across your code via [gobot issue #258](https://github.com/hybridgroup/gobot/issues/258) The DS18B20 part of your code works fine on my Raspberry Pi (I did not test the gpio stuff), so I wonder if you would mind to re-use it?

If so, could you please state under which license? [Gobot uses the Apache License Version 2.0](https://github.com/hybridgroup/gobot/blob/master/LICENSE.txt), so I guess this would be an easy choice.

Thank you very much in advance!

**Comment by aqua** [comment]
Fixed in 54f0d4e (noticed this six years later)
